services:
  bot:
    build: .
    image: youtube-downloader-telegram
    volumes:
      - .:/bot
    env_file:
      - .env
    restart: always

  db:
    image: postgres:latest
    ports:
      - 5650:5432
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
