services:
  bot:
    build: .
    image: youtube-downloader-telegram
    container_name: youtube-downloader
    volumes:
      - ./src:/bot/src
    environment:
      - TOKEN
      - ALLOWED_USER_IDS
    restart: always
